### ISSUE TITLE
Set facets manually

### ISSUE THREAD

**Issue by hugoruscitti** [edhuardotierrez/ember-visual-search#1]
Hi!, i really like this addon but i find some issues trying to set the initial value of the filters programmatically. Is possible to set or change the filters value?

I was trying to add a simple button next to the ember-visual-search component to preset some filters when the user click on it, something similar to this dropdown next to the github's filters.

![image](https://user-images.githubusercontent.com/99183/55846673-ed4d7880-5b1c-11e9-8587-fa9122e06f9b.png)

**Comment by hugoruscitti** [comment]
Oh, i was find a parameter called `defaultFacets`, that allow me to set the filter initial value, but this only works the first time, if i change this property again the component don't update.

Do you have any advice?

**Comment by edhuardotierrez** [comment]
Hi, thanks for your point of view.
I uploaded an update (v0.1.9) and here's what you can do:

_Simple Example_

**Controller:**
```javascript
variableInYourContext: null, // <- variable for 'registeredAs' in component
actions: {
    changeDefaultFacets() {
      let searchComponent = this.get('variableInYourContext');
      let newFacets = [
        {
          'key': 'other-key', // key
          'title': 'OtherKey', // key title (optional)
          'value': 'Your other value '
        }
      ];
      searchComponent.set('defaultFacets', newFacets);
      searchComponent.resetDefaults(); // to update
    }
}
```

**Template:**
```hbs
 {{visual-search
          ...
          defaultFacets=myDefaultFacets
          registerAs=variableInYourContext 
          ...
}}
```

Please try this.

**Comment by hugoruscitti** [comment]
Thanks @edhuardotierrez !!!, now works well, but the only downside i see is that `resetDefaults` function seems to enable the dropdown menu automatically. Is there any way to prevent the focus on the input and the dropdown menu when i call the `resetDefaults` function?.

It seems a side effect hard to fix, i really appreciate your support and i understand if it is not essential. Thanks
